export const PROJECTS = [
  {
    id: 1,
    name: "AetherMeet",
    subtitle: "Real-Time Video & Chat Platform",
    year: "2025",
    image: "/assets/images/aethermeet.png",
    desc: "Full-stack platform featuring encrypted room access, live chat, and media sharing for 50+ concurrent users. Built 10+ RESTful APIs using Node.js to manage room lifecycles, authentication, and messaging workflows. Integrated Socket.io for sub-100ms real-time updates and Redis caching with 30-min TTL for 30% performance improvement.",
    tech: ["Node.js", "Express.js", "Socket.io", "Redis", "MongoDB", "JWT"],
    github: "https://github.com/deepanshusingla076/Aethermeet",
    live: "https://aethermeet-web.onrender.com",
  },
  {
    id: 2,
    name: "B-ware",
    subtitle: "AI Claim Verification Platform",
    year: "Feb 2026",
    image: "/assets/images/b-ware.png",
    desc: "AI-driven claim verification platform built with NLP microservices for evidence extraction and contextual analysis. Designed credibility scoring pipelines that validate incoming claims in real time and support faster decision-making workflows. Optimized backend response times using Redis caching and shipped containerized services with Docker for reliable deployment.",
    tech: [
      "React.js",
      "Node.js",
      "Express.js",
      "MySQL",
      "Redis",
      "Python (NLP)",
      "Docker",
    ],
  },
  {
    id: 3,
    name: "FiSight",
    subtitle: "Financial Analytics Platform",
    year: "2025",
    image: "/assets/images/fisight.png",
    desc: "Analytics engine that processes 50,000+ financial records for automated predictive spending insights. Architected hybrid MongoDB + MySQL backend for high data consistency. Trained and evaluated 4 ML models targeting 92% accuracy. Built data pipelines for automated financial behavior analysis.",
    tech: [
      "Python",
      "Machine Learning",
      "Node.js",
      "FastAPI",
      "MongoDB",
      "MySQL",
    ],
    github: "https://github.com/deepanshusingla076/FiSight",
    live: "https://fi-sight.vercel.app/",
  },
  {
    id: 4,
    name: "HireSight AI",
    subtitle: "AI-Powered Resume Intelligence Platform",
    year: "2025",
    image: "/assets/images/hireSight.png",
    desc: "Production-ready AI resume analysis platform powered by Google Gemini 2.0. Delivers smart resume-to-job matching, skill-gap analysis, actionable insights, and AI-generated interview prep questions. Uses a real dataset of 63,764+ job descriptions with modern glassmorphism UI and keyword-based smart search.",
    tech: [
      "Next.js",
      "TypeScript",
      "Gemini AI",
      "Node.js",
      "MongoDB",
      "Python",
    ],
    github: "https://github.com/deepanshusingla076/hireSight-AI",
    live: "https://hire-sight-ai-nine.vercel.app/",
  },
  {
    id: 5,
    name: "Quizz",
    subtitle: "Quiz Platform — Microservices Architecture",
    year: "2025",
    image: "/assets/images/quizz.png",
    desc: "Scalable quiz platform built with Spring Boot microservices. Implemented authentication, question bank, result management, AI-powered quiz generation, and API gateway services. Automated service orchestration with batch scripts, Eureka service discovery, and secure role-based access control.",
    tech: ["Spring Boot", "Java", "Microservices", "JWT", "React", "Eureka"],
    github: "https://github.com/deepanshusingla076/quiz-master",
  },
  {
    id: 6,
    name: "Rizzard University",
    subtitle: "AI-Powered University Platform",
    year: "2024",
    image: "/assets/images/rizzard.png",
    desc: "Full-stack university web app with course listings, event registration, and user management. Integrated advanced AI chatbot via Grok (xAI) APIs for real-time support. Implemented secure backend proxy endpoints and dynamic API key management.",
    tech: ["Node.js", "Express", "MongoDB", "EJS", "Grok AI", "JavaScript"],
    github: "https://github.com/deepanshusingla076/rizzard_university",
    live: "https://rizzard-university.vercel.app/",
  },
];

export const EXPERIENCE = [
  {
    role: "Web Development Intern",
    company: "TechOctaNet",
    location: "Remote",
    period: "Feb 2025 – Mar 2025",
    bullets: [
      "Designed and deployed responsive websites using React.js, Bootstrap, and MongoDB with 99.99% uptime.",
      "Managed CI/CD pipelines using Docker and Git for automated deployment workflows.",
      "Ensured 100% deployment success rate with integrated monitoring and modification services.",
    ],
  },
  {
    role: "Open Source Contributor",
    company: "GirlScript Summer of Code (GSSoC)",
    location: "Remote",
    period: "Jul 2025 – Present",
    bullets: [
      "Contributed to 10+ repositories, engineering features and resolving bugs while maintaining high code quality.",
      "Collaborated using Git workflows, managing pull requests and participating in peer code reviews.",
      "Applied modular design principles to enhance scalability and maintainability across projects.",
    ],
  },
];

export const SKILLS = {
  Languages: ["Java", "Python", "JavaScript", "TypeScript"],
  Frontend: ["React.js", "Next.js", "Tailwind CSS", "Redux Toolkit"],
  Backend: [
    "Node.js",
    "Express.js",
    "Spring Boot",
    "FastAPI",
    "REST APIs",
    "Socket.IO",
    "JWT",
  ],
  Databases: ["MongoDB", "MySQL", "Firebase", "Redis", "SQL"],
  "Cloud & DevOps": [
    "AWS (EC2, S3, IAM)",
    "Docker",
    "CI/CD Pipelines",
    "Firebase Hosting",
  ],
  "Tools & Platforms": ["Git", "GitHub", "Postman", "VS Code", "Linux"],
  Concepts: ["OOPs", "Microservices", "System Design", "Problem Solving"],
};

export const CERTS = [
  {
    name: "Microsoft - Introduction to Generative AI and Agents",
    issuer: "Microsoft",
    year: "2026",
    note: "Introduction to generative AI and agents",
    image: "/assets/certificates/gen_ai.png",
  },
  {
    name: "Google Cloud - Introduction to Generative AI",
    issuer: "Google Cloud",
    year: "2026",
    note: "Generative AI completion badge",
    image: "/assets/certificates/generative-ai.png",
  },
  {
    name: "ThingQbator Certificate",
    issuer: "ThingQbator",
    year: "2025",
    note: "MERN stack certificate",
    image: "/assets/certificates/thingQbator.png",
  },
  {
    name: "GeeksforGeeks - 160 Days of Problem Solving",
    issuer: "GeeksforGeeks",
    year: "2024",
    note: "22-week problem solving course completion certificate",
    image: "/assets/certificates/gfg_160.png",
  },
  {
    name: "Coding Ninjas - Introduction to Python",
    issuer: "Coding Ninjas",
    year: "2023",
    note: "Introduction to Python",
    image: "/assets/certificates/python-cn.png",
  },
  {
    name: "HackerRank - JavaScript (Basic)",
    issuer: "HackerRank",
    year: "2024",
    note: "JavaScript (Basic) skill certification",
    image: "/assets/certificates/javascript.png",
  },
  {
    name: "Duke University - Cloud Computing",
    issuer: "Duke University",
    year: "2025",
    note: "Cloud computing certificate",
    image: "/assets/certificates/cloud-eng.png",
  },
  {
    name: "Akamai - Networking Fundamentals",
    issuer: "Akamai Technologies / Coursera",
    year: "2024",
    note: "Networking Fundamentals certificate",
    image: "/assets/certificates/Network_Academy_Certificate.png",
  },
  {
    name: "Cisco - Cyber Security",
    issuer: "Cisco Networking Academy",
    year: "2025",
    note: "Cybersecurity Essentials",
    image: "/assets/certificates/cyber-cisco.png",
  },
];

export const HACKATHONS = [
  {
    name: "Hack2skill Hackathon",
    type: "Hackathon",
    year: "2025",
    image: "/assets/certificates/Hack2skill.png",
    note: "Google Cloud Agent AI Day",
  },
  {
    name: "GDG Hacks",
    type: "Google Developer Groups",
    year: "2025",
    image: "/assets/certificates/gdg.png",
  },
  {
    name: "BharatTechperience 2.0",
    type: "National Hackathon",
    year: "2025",
    image: "/assets/certificates/sviet.png",
  },
  {
    name: "ComSoc HackX 2025",
    type: "Hackathon",
    year: "2025",
    image: "/assets/certificates/comsoc.png",
  },
  {
    name: "Hackentine Hackathon",
    type: "Coding Ninjas",
    year: "2025",
    image: "/assets/certificates/coding ninja hackerthon.jpg",
    note: "Coding Ninjas Hackathon",
  },
  {
    name: "GSSoC 2025 Contributor",
    type: "Open Source",
    year: "2025",
    image: "/assets/certificates/gssoc.png",
    note: "GirlScript Summer of Code 2025 contributor badge",
  },
];
